### ISSUE TITLE
Project cannot be installed without manual package management.

### ISSUE THREAD

**Issue by fake-name** [jkehler/unshortenit#20]
Briefly (ignore the platform and repo differences. The issue is also present in cpython, and my repo matches yours at the point I encountered the issue):

```
durr@rwpscrape /m/S/S/ReadableWebProxy> pypy3 -m pip install git+https://github.com/fake-name/unshortenit.git
Collecting git+https://github.com/fake-name/unshortenit.git
  Cloning https://github.com/fake-name/unshortenit.git to /tmp/pip-dcg6fu3e-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-dcg6fu3e-build/setup.py", line 6, in <module>
        import unshortenit
      File "/tmp/pip-dcg6fu3e-build/unshortenit/__init__.py", line 8, in <module>
        from .base import unwrap_30x_only
      File "/tmp/pip-dcg6fu3e-build/unshortenit/base.py", line 10, in <module>
        import requests
    ImportError: No module named 'requests'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-dcg6fu3e-build/

```

Basically, `setup.py` imports `unshortenit/__init__.py`, which imports `unshortenit/base.py`, which imports `requests`. This is done while parsing the `setup.py` file, *before* the `install_requires` directives are parsed. This means it tries to import `requests` before it's actually processed the dependencies (and installed them).

This can be worked around by manually installing `requests` beforehand, but basically the way the version is currently read is broken. 

I think this is what https://github.com/jkehler/unshortenit/issues/10 was trying to get at, but was not clear with.

**Comment by jkehler** [comment]
This should be fixed in the 0.4.0 release.
