### ISSUE TITLE
Syntax Error in 0.4.0 package?

### ISSUE THREAD

**Issue by NetwarSystem** [jkehler/unshortenit#32]
My version from pip freeze is:

> unshortenit==0.4.0

And it's throwing this error:

> Traceback (most recent call last):
>   File "./checkurl", line 3, in <module>
>     from unshortenit import UnshortenIt
>   File "/usr/local/lib/python2.7/dist-packages/unshortenit/__init__.py", line 12, in <module>
>     from .unshortenit import UnshortenIt    # noqa
>   File "/usr/local/lib/python2.7/dist-packages/unshortenit/unshortenit.py", line 24
>     def __init__(self, default_timeout: int = 30, default_headers: dict = None):
>                                       ^
> SyntaxError: invalid syntax

Is this because I still have Python 2.7??

**Comment by jkehler** [comment]
Yup the latest version of this library no longer supports Python 2.7

**Comment by NetwarSystem** [comment]
yeah, just whipped up a virtualenv to try that.

So this is closed :-)
