### ISSUE TITLE
It doesn't work unless a link has http(s):// in it

### ISSUE THREAD

**Issue by Dreysman** [jkehler/unshortenit#8]
I believe this could easily be fixed by simply adding http to the arg if it's missing, or some other change to the code, however I do not know python well nor do I know this project well.

**Comment by jkehler** [comment]
It should be up the user to add the http(s):// to URL's before passing it to unshortenit. I don't see the need to implement this in the module.

**Comment by Dreysman** [comment]
Alright, just thought it would be convenient, since I often paste it in directly without http(s):// before, but I made a bash wrapper that does this for me any way.
